packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  highlight.js: true
  vue-demi: true

onlyBuiltDependencies:
  - esbuild
  - highlight.js
  - vue-demi

patchedDependencies:
  "@v-c/picker@1.3.2": patches/@v-c__picker@1.3.2.patch
